Repository kang123077/SlimeGG, pull requests merged in 2022-12, with the labels that each got.

#11 6 monster refactoring
  SlimeGG/Assets/Prefabs/Monsters/Monster.prefab
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Beast.png
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Beast.png.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Dark.png
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Dark.png.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Lava.png
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Lava.png.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Ore.png
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Ore.png.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Water.png
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Water.png.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/egg.png
  SlimeGG/Assets/Resources/Sprites/Monsters/egg.png.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/monster_test.png
  SlimeGG/Assets/Scenes/SampleScene.unity
  SlimeGG/Assets/Scripts/Maps/Generators/SocketGenerator.cs
  SlimeGG/Assets/Scripts/Maps/Generators/TileSetGenerator.cs
  SlimeGG/Assets/Scripts/Maps/SocketController.cs
  SlimeGG/Assets/Scripts/Maps/TileBaseController.cs
  SlimeGG/Assets/Scripts/Maps/TileSetController.cs
  SlimeGG/Assets/Scripts/Monsters/Generators/MonsterGenerator.cs
  SlimeGG/Assets/Scripts/Monsters/MonsterBaseController.cs
  SlimeGG/Assets/Scripts/Monsters/VO/MonsterInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration.meta
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration/EggType.cs
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration/EggType.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration/InfantType.cs
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration/InfantType.cs.meta
  SlimeGG/ProjectSettings/Physics2DSettings.asset
Labels: bug, enhancement

#13 [Add] Animation for Monster
  SlimeGG/Assets/Prefabs/Monsters/Monster.prefab
  SlimeGG/Assets/Resources/Animations.meta
  SlimeGG/Assets/Resources/Animations/Monsters.meta
  SlimeGG/Assets/Resources/Animations/Monsters/Infants.meta
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore.meta
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore/Controller.controller
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore/Controller.controller.meta
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore/L.anim
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore/L.anim.meta
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore/R.anim
  SlimeGG/Assets/Resources/Animations/Monsters/Infants/Ore/R.anim.meta
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Ore.png
  SlimeGG/Assets/Resources/Sprites/Monsters/Infants/Ore.png.meta
  SlimeGG/Assets/Scenes/SampleScene.unity
  SlimeGG/Assets/Scripts/Commons/VO.meta
  SlimeGG/Assets/Scripts/Commons/VO/DirectionState.cs
  SlimeGG/Assets/Scripts/Commons/VO/DirectionState.cs.meta
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs.meta
  SlimeGG/Assets/Scripts/Monsters/Generators/MonsterGenerator.cs
  SlimeGG/Assets/Scripts/Monsters/MonsterBaseController.cs
  SlimeGG/Assets/Scripts/Monsters/VO/GrowthState.cs
  SlimeGG/Assets/Scripts/Monsters/VO/GrowthState.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/MonsterInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration/EggType.cs
  SlimeGG/Assets/Scripts/Monsters/VO/TypesByGeneration/InfantType.cs
Labels: enhancement, good first issue

#15 7 update monster&tile set info
  SlimeGG/Assets/Resources/Jsons.meta
  SlimeGG/Assets/Resources/Jsons/Monsters.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Eggs.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Infants.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Infants/Ore.Json
  SlimeGG/Assets/Resources/Jsons/Monsters/Infants/Ore.Json.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Lv2s.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Lv3s.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Lv4s.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Skills.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Skills/Charge.json
  SlimeGG/Assets/Resources/Jsons/Monsters/Skills/Charge.json.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/Skills/Scratch.json
  SlimeGG/Assets/Resources/Jsons/Monsters/Skills/Scratch.json.meta
  SlimeGG/Assets/Resources/Jsons/MosterInfoBySpecies.json
  SlimeGG/Assets/Resources/Jsons/MosterInfoBySpecies.json.meta
  SlimeGG/Assets/Resources/Jsons/SkillDB.json
  SlimeGG/Assets/Resources/Jsons/SkillDB.json.meta
  SlimeGG/Assets/Resources/Jsons/Test.json
  SlimeGG/Assets/Resources/Jsons/Test.json.meta
  SlimeGG/Assets/Scenes/SampleScene.unity
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs
  SlimeGG/Assets/Scripts/Maps/VO/TileShape.cs
  SlimeGG/Assets/Scripts/Monsters/Generators/MonsterGenerator.cs
  SlimeGG/Assets/Scripts/Monsters/VO/GrowthState.cs
  SlimeGG/Assets/Scripts/Monsters/VO/GrowthStateInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/GrowthStateInfo.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/MonsterInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/SkillInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/SkillInfo.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/SkillName.cs
  SlimeGG/Assets/Scripts/Monsters/VO/SkillName.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/SpeciesInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/SpeciesInfo.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/SpeciesName.cs
  SlimeGG/Assets/Scripts/Monsters/VO/SpeciesName.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/StatInfo.cs
  SlimeGG/Assets/Scripts/Monsters/VO/StatInfo.cs.meta
  SlimeGG/Assets/Scripts/Monsters/VO/TypeName.cs
  SlimeGG/Assets/Scripts/Monsters/VO/TypeName.cs.meta
  SlimeGG/Assets/Scripts/TypeSet.cs
  SlimeGG/Assets/Scripts/TypeSet.cs.meta
  SlimeGG/Assets/Scripts/UIs/PopupUIController.cs
Labels: enhancement

#26 22 enhancing battle ai
  SlimeGG/Assets/Resources/Battles.meta
  SlimeGG/Assets/Resources/Jsons/Fields/Normal.json
  SlimeGG/Assets/Resources/Sprites/Fields.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/ground_400_300.png
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/ground_400_300.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/ground_4_3.png
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/ground_4_3.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_01.png
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_01.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_02.png
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_02.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_03.png
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_03.png.meta
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scenes/SampleScene.unity
  SlimeGG/Assets/Scripts/Effects/Controller/BulletController.cs
  SlimeGG/Assets/Scripts/Maps/Controller/FieldController.cs
  SlimeGG/Assets/Scripts/Maps/Objects/FieldInfo.cs
  SlimeGG/Assets/Scripts/Monsters/Controllers/MonsterBaseController.cs
  SlimeGG/Assets/Scripts/Monsters/Controllers/MonsterBattleController.cs
Labels: enhancement
