Repository kang123077/SlimeGG, pull requests merged in 2023-02, with the labels that each got.

#74 70 inventory separation
  SlimeGG/Assets/Prefabs/Inventories/StarPrefab.prefab
  SlimeGG/Assets/Prefabs/Inventories/StarPrefab.prefab.meta
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs.meta
  SlimeGG/Assets/Scripts/Inventories/Controllers/EvolutionCaseController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ExpModuleController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ExpSingleController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/MonsterInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SkillInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/StatSlotController.cs
  SlimeGG/Assets/Scripts/Objects/Common/BasicStatEnum.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: enhancement

#75 66 save load
  SlimeGG/Assets/Resources/Jsons/Save/Items.json
  SlimeGG/Assets/Resources/Jsons/Save/Monsters.json
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scenes/MainMenuScene.unity
  SlimeGG/Assets/Scripts/Commons/Controller/BasicCameraMoveController.cs
  SlimeGG/Assets/Scripts/Commons/Functions/SaveFunction.cs
  SlimeGG/Assets/Scripts/Commons/LocalStorage.cs
  SlimeGG/Assets/Scripts/Commons/Managers/MainGameManager.cs
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonManager.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ExpModuleController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/MonsterInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/StatSlotController.cs
  SlimeGG/Assets/Scripts/Rewards/Controllers.meta
  SlimeGG/Assets/Scripts/Rewards/Controllers/ChoiceController.cs
  SlimeGG/Assets/Scripts/Rewards/Managers/RewardManager.cs
  SlimeGG/Assets/Scripts/Rewards/Objects/RewardType.cs
  SlimeGG/Assets/Scripts/Settings.meta
  SlimeGG/Assets/Scripts/Settings/Controllers.meta
  SlimeGG/Assets/Scripts/Settings/Managers.meta
  SlimeGG/Assets/Scripts/Settings/Managers/SettingManager.cs
  SlimeGG/Assets/Scripts/Settings/Managers/SettingManager.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/FontResizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/FontResizeController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/GridSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/GridSizeController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement

#76 Add: Popup ui for Item info
  SlimeGG/Assets/Resources/Jsons/Items/Dagger.json
  SlimeGG/Assets/Resources/Jsons/Items/SuperDagger.json
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Objects/Dictionary/ItemDictionaryStat.cs
  SlimeGG/Assets/Scripts/UIs/Controller/InfoWindowController.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement

#77 67 feeding exp
  SlimeGG/Assets/Prefabs/Inventories/ExpSinglePrefab.prefab
  SlimeGG/Assets/Scenes/MainMenuScene.unity
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/EvolutionCaseController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ExpModuleController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ExpSingleController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/MonsterInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SkillInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/StatSlotController.cs
  SlimeGG/Assets/Scripts/Settings/Managers/SettingManager.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: enhancement

#79 68 commerce
  SlimeGG/Assets/Resources/Jsons/Save/Currency.json
  SlimeGG/Assets/Resources/Jsons/Save/Currency.json.meta
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Commons/Functions/CommerceFunction.cs
  SlimeGG/Assets/Scripts/Commons/Functions/CommerceFunction.cs.meta
  SlimeGG/Assets/Scripts/Commons/Functions/SaveFunction.cs
  SlimeGG/Assets/Scripts/Commons/LocalStorage.cs
  SlimeGG/Assets/Scripts/Commons/Managers/DataManager.cs
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SellController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SellController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/CommerceController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/CommerceController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: enhancement

#80 71 reward
  SlimeGG/Assets/Prefabs/Inventories/CommercePrefab.prefab
  SlimeGG/Assets/Prefabs/Inventories/CommercePrefab.prefab.meta
  SlimeGG/Assets/Prefabs/Inventories/InventoryPrefab.prefab
  SlimeGG/Assets/Prefabs/Inventories/InventoryPrefab.prefab.meta
  SlimeGG/Assets/Prefabs/Rewards/ChoicePrefab.prefab
  SlimeGG/Assets/Prefabs/Rewards/RewardPrefab.prefab
  SlimeGG/Assets/Prefabs/Rewards/RewardPrefab.prefab.meta
  SlimeGG/Assets/Prefabs/UIs/InfoWindowPrefab.prefab
  SlimeGG/Assets/Prefabs/UIs/InfoWindowPrefab.prefab.meta
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Commons/LocalStorage.cs
  SlimeGG/Assets/Scripts/Objects/Common/DirectionEnum.cs
  SlimeGG/Assets/Scripts/Objects/Common/DirectionEnum.cs.meta
  SlimeGG/Assets/Scripts/Rewards.meta
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectMoveController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectMoveController.cs.meta
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: enhancement

#82 Remove: Delete numberRestrictPerSide
  SlimeGG/Assets/Prefabs/Monsters/MonsterForBattle.prefab
  SlimeGG/Assets/Resources/Jsons/Fields/Normal.json
  SlimeGG/Assets/Resources/Jsons/Save/Monsters.json
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Battles/Controller/FieldController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/MonsterBattleController.cs
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Battles/Objects/FieldInfo.cs
Labels: enhancement

#83 Add: Basic structure for Reward
  SlimeGG/Assets/Prefabs/Rewards/RewardPrefab.prefab
  SlimeGG/Assets/Resources/Jsons/Items/Dagger.json
  SlimeGG/Assets/Resources/Jsons/Monsters/BabySpirit.Json
  SlimeGG/Assets/Resources/Jsons/Save/Items.json
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scenes/MainMenuScene.unity
  SlimeGG/Assets/Scripts/Inventories/Controllers/EvolutionCaseController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ExpModuleController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/MonsterInfoController.cs
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
Labels: enhancement

#86 85 entry UI integration
  SlimeGG/Assets/Prefabs/Battles/Fields/EntrySlots/slot.prefab
  SlimeGG/Assets/Prefabs/Battles/Fields/Grounds.meta
  SlimeGG/Assets/Prefabs/Battles/Fields/Obstacles.meta
  SlimeGG/Assets/Prefabs/Battles/UIs/Monster Info UI.prefab
  SlimeGG/Assets/Prefabs/Battles/UIs/Monster Info UI.prefab.meta
  SlimeGG/Assets/Prefabs/Battles/UIs/SideDrawer.prefab
  SlimeGG/Assets/Prefabs/Battles/UIs/SideDrawer.prefab.meta
  SlimeGG/Assets/Prefabs/Inventories/ContentPrefab.prefab
  SlimeGG/Assets/Resources/Jsons/Entries/Test.json
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/4_3_barrier.png
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/4_3_barrier.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/4_3_ground.png
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/4_3_ground.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/barrier_dummy.png
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/barrier_dummy.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/field_dummy.png
  SlimeGG/Assets/Resources/Sprites/Fields/Grounds/field_dummy.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_01.png
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_01.png.meta
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_02.png
  SlimeGG/Assets/Resources/Sprites/Fields/Obstacles/obs_03.png
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Battles/Controller/EntrySlotController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/FieldController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/MonsterBattleController.cs
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Battles/Manager/EnrtySlotManager.cs
  SlimeGG/Assets/Scripts/Battles/Manager/EnrtySlotManager.cs.meta
  SlimeGG/Assets/Scripts/Battles/Objects/FieldInfo.cs
  SlimeGG/Assets/Scripts/Commons/LocalStorage.cs
  SlimeGG/Assets/Scripts/Commons/Managers/MainGameManager.cs
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs
  SlimeGG/Assets/Scripts/Dungeons/Controller/StageController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Monsters.meta
  SlimeGG/Assets/Scripts/Monsters/Controllers.meta
  SlimeGG/Assets/Scripts/Monsters/Controllers/MonsterBattleUIController.cs
  SlimeGG/Assets/Scripts/Monsters/Enums.meta
  SlimeGG/Assets/Scripts/Monsters/Generators.meta
  SlimeGG/Assets/Scripts/Monsters/Objects.meta
  SlimeGG/Assets/Scripts/Monsters/VO.meta
  SlimeGG/Assets/Scripts/UIs/Controller/GridSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectMoveController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/SideDrawerController.cs
  SlimeGG/Assets/Scripts/UIs/Generators/GridCellGenerator.cs
  SlimeGG/Assets/Scripts/UIs/Generators/GridCellGenerator.cs.meta
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement

#89 Add: Basic Structure For Reward
  SlimeGG/Assets/Resources/Jsons/Items/Dagger.json
  SlimeGG/Assets/Resources/Jsons/Items/SuperDagger.json
  SlimeGG/Assets/Resources/Jsons/Items/WoodenStaff.json
  SlimeGG/Assets/Resources/Jsons/Items/WoodenStaff.json.meta
  SlimeGG/Assets/Resources/Jsons/Monsters/BabySpirit.Json
  SlimeGG/Assets/Resources/Jsons/Monsters/BundleFur.Json
  SlimeGG/Assets/Resources/Jsons/Monsters/Eartipede.Json
  SlimeGG/Assets/Resources/Jsons/Monsters/MudBall.Json
  SlimeGG/Assets/Resources/Jsons/Monsters/Sleepion.Json
  SlimeGG/Assets/Resources/Jsons/Monsters/Sneaklower.Json
  SlimeGG/Assets/Resources/Jsons/Save/Currency.json
  SlimeGG/Assets/Resources/Jsons/Save/Items.json
  SlimeGG/Assets/Resources/Jsons/Save/Monsters.json
  SlimeGG/Assets/Resources/Jsons/Skills/Charge.json
  SlimeGG/Assets/Resources/Jsons/Skills/Spit.json
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scripts/Battles/Controller/EntrySlotController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/FieldController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/MonsterBattleController.cs
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Commons/Functions/CommerceFunction.cs
  SlimeGG/Assets/Scripts/Commons/Functions/GeneratorFunction.cs
  SlimeGG/Assets/Scripts/Commons/Functions/SaveFunction.cs
  SlimeGG/Assets/Scripts/Commons/LocalDictionary.cs
  SlimeGG/Assets/Scripts/Commons/LocalStorage.cs
  SlimeGG/Assets/Scripts/Commons/Managers/DataManager.cs
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs
  SlimeGG/Assets/Scripts/Dungeons/Controller/StageController.cs
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonManager.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/MonsterInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SlotController.cs
  SlimeGG/Assets/Scripts/Objects/Common/BasicStatEnum.cs
  SlimeGG/Assets/Scripts/Objects/Dictionary/ItemDictionaryStat.cs
  SlimeGG/Assets/Scripts/Objects/Dictionary/MonsterDictionaryStat.cs
  SlimeGG/Assets/Scripts/Objects/Save/MonsterSaveStat.cs
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/CommerceController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectMoveController.cs
  SlimeGG/Assets/Scripts/UIs/Generators/GridCellGenerator.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement

#95 Feat: Leftover For Dungeon Editor
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonEditor.cs
Labels: duplicate, editor

#97 Develop
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonEditor.cs
Labels: duplicate, editor

#98 91 reward reroll
  SlimeGG/Assets/Prefabs/Rewards/RewardPrefab.prefab
  SlimeGG/Assets/Resources/Jsons/Monsters/BabySpirit.Json
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scripts/Battles/Controller/EntrySlotController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/MonsterBattleController.cs
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonManager.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SlotController.cs
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectMoveController.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: bug, enhancement

#101 72 battle tile
  SlimeGG/Assets/Prefabs/Battles/Fields/PlaceableSlot.meta
  SlimeGG/Assets/Prefabs/Battles/Fields/PlaceableSlot/PlaceableSlotPrefab.prefab
  SlimeGG/Assets/Prefabs/Battles/Fields/PlaceableSlot/PlaceableSlotPrefab.prefab.meta
  SlimeGG/Assets/Resources/Jsons/Fields/Normal.json
  SlimeGG/Assets/Resources/Jsons/Fields/rrr.json
  SlimeGG/Assets/Resources/Jsons/Fields/rrr.json.meta
  SlimeGG/Assets/Resources/Jsons/Fields/tetet.json
  SlimeGG/Assets/Resources/Jsons/Fields/tetet.json.meta
  SlimeGG/Assets/Scenes/Editors.meta
  SlimeGG/Assets/Scenes/Editors/BasicEditor.unity
  SlimeGG/Assets/Scenes/Editors/BasicEditor.unity.meta
  SlimeGG/Assets/Scenes/Editors/DungeonEditorScene.unity
  SlimeGG/Assets/Scenes/Editors/DungeonEditorScene.unity.meta
  SlimeGG/Assets/Scenes/Editors/FieldEditor.unity
  SlimeGG/Assets/Scenes/Editors/FieldEditor.unity.meta
  SlimeGG/Assets/Scripts/Battles/Controller/EntrySlotController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/MonsterBattleController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/PlaceableSlotController.cs
  SlimeGG/Assets/Scripts/Battles/Controller/PlaceableSlotController.cs.meta
  SlimeGG/Assets/Scripts/Battles/Manager/EnrtySlotManager.cs
  SlimeGG/Assets/Scripts/Battles/Manager/FieldEditor.cs
  SlimeGG/Assets/Scripts/Battles/Manager/FieldEditor.cs.meta
  SlimeGG/Assets/Scripts/Battles/Objects/EntrySlotSaveStat.cs
  SlimeGG/Assets/Scripts/Battles/Objects/EntrySlotSaveStat.cs.meta
  SlimeGG/Assets/Scripts/Battles/Objects/FieldSaveStat.cs
  SlimeGG/Assets/Scripts/Battles/Objects/FieldSaveStat.cs.meta
  SlimeGG/Assets/Scripts/Commons/Functions/SaveFunction.cs
  SlimeGG/Assets/Scripts/Commons/Managers/BasicEditor.cs
  SlimeGG/Assets/Scripts/Commons/Managers/BasicEditor.cs.meta
  SlimeGG/Assets/Scripts/Commons/Managers/IBasicEditor.cs
  SlimeGG/Assets/Scripts/Commons/Managers/IBasicEditor.cs.meta
  SlimeGG/Assets/Scripts/Commons/Managers/MainGameManager.cs
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs
  SlimeGG/Assets/Scripts/Dungeons/Controller/MoreChoiceController.cs
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonEditor.cs
  SlimeGG/Assets/Scripts/Objects/Common/BasicStat.cs
  SlimeGG/Assets/Scripts/Objects/Common/BasicStatEnum.cs
  SlimeGG/Assets/Scripts/UIs/Generators/GridCellGenerator.cs
  SlimeGG/Assets/Scripts/UIs/Managers/MouseEventManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement, good first issue, editor

#106 102 editor squad
  SlimeGG/Assets/Prefabs/UIs/Tracking Window/ImageChoicePrefab.prefab
  SlimeGG/Assets/Prefabs/UIs/Tracking Window/ImageChoicePrefab.prefab.meta
  SlimeGG/Assets/Resources/Jsons/Save/Monsters.json
  SlimeGG/Assets/Scenes/Editors/SquadEditor.unity
  SlimeGG/Assets/Scenes/Editors/SquadEditor.unity.meta
  SlimeGG/Assets/Scripts/Battles/Controller/EntrySlotController.cs
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Battles/Manager/FieldEditor.cs
  SlimeGG/Assets/Scripts/Battles/Manager/SquadEditor.cs
  SlimeGG/Assets/Scripts/Battles/Manager/SquadEditor.cs.meta
  SlimeGG/Assets/Scripts/Battles/Objects/MonsterBattleInfo.cs
  SlimeGG/Assets/Scripts/Commons/Functions/CommonFunctions.cs
  SlimeGG/Assets/Scripts/Commons/Functions/MonsterCommonFunction.cs
  SlimeGG/Assets/Scripts/Commons/Functions/SaveFunction.cs
  SlimeGG/Assets/Scripts/Commons/Managers/BasicEditor.cs
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs
  SlimeGG/Assets/Scripts/Dungeons/Controller/MoreChoiceController.cs
  SlimeGG/Assets/Scripts/Objects/Save/MonsterSaveStat.cs
  SlimeGG/Assets/Scripts/UIs/Managers/MouseEventManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement, editor

#109 Closes #108
  SlimeGG/Assets/Resources/Jsons/Save/Currency.json
  SlimeGG/Assets/Resources/Jsons/Save/Items.json
  SlimeGG/Assets/Resources/Jsons/Save/Journey.json
  SlimeGG/Assets/Resources/Jsons/Save/Monsters.json
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Dungeons/Controller/StageController.cs
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonManager.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/SlotController.cs
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
Labels: bug, enhancement

#110 Close #88 event module
  SlimeGG/Assets/Prefabs/Events.meta
  SlimeGG/Assets/Prefabs/Events/EventModulePrefab.prefab
  SlimeGG/Assets/Prefabs/Events/EventModulePrefab.prefab.meta
  SlimeGG/Assets/Prefabs/Inventories/InventoryPrefab.prefab
  SlimeGG/Assets/Prefabs/UIs/GridCells.meta
  SlimeGG/Assets/Prefabs/UIs/GridCells/TextChoiceButtonPrefab.prefab
  SlimeGG/Assets/Prefabs/UIs/GridCells/TextChoiceButtonPrefab.prefab.meta
  SlimeGG/Assets/Resources/Jsons/Events.meta
  SlimeGG/Assets/Resources/Jsons/Events/Test.json
  SlimeGG/Assets/Resources/Jsons/Events/Test.json.meta
  SlimeGG/Assets/Resources/Jsons/Save/DungeonHistory.json
  SlimeGG/Assets/Resources/Jsons/Save/Journey.json
  SlimeGG/Assets/Resources/Sprites/Backgrounds.meta
  SlimeGG/Assets/Resources/Sprites/Npcs.meta
  SlimeGG/Assets/Scenes/DungeonMapScene.unity
  SlimeGG/Assets/Scenes/MainMenuScene.unity
  SlimeGG/Assets/Scripts/Commons/Functions/GeneratorFunction.cs
  SlimeGG/Assets/Scripts/Commons/LocalStorage.cs
  SlimeGG/Assets/Scripts/Commons/SettingVariables.cs
  SlimeGG/Assets/Scripts/Commons/VO/PathInfo.cs
  SlimeGG/Assets/Scripts/Dungeons/Controller/StageController.cs
  SlimeGG/Assets/Scripts/Dungeons/Managers/DungeonManager.cs
  SlimeGG/Assets/Scripts/Events.meta
  SlimeGG/Assets/Scripts/Events/Controller.meta
  SlimeGG/Assets/Scripts/Events/Controller/EventController.cs
  SlimeGG/Assets/Scripts/Events/Controller/EventController.cs.meta
  SlimeGG/Assets/Scripts/Events/Objects.meta
  SlimeGG/Assets/Scripts/Events/Objects/EventChoiceStat.cs
  SlimeGG/Assets/Scripts/Events/Objects/EventChoiceStat.cs.meta
  SlimeGG/Assets/Scripts/Events/Objects/EventRewardStat.cs
  SlimeGG/Assets/Scripts/Events/Objects/EventRewardStat.cs.meta
  SlimeGG/Assets/Scripts/Events/Objects/EventSaveStat.cs
  SlimeGG/Assets/Scripts/Events/Objects/EventSaveStat.cs.meta
  SlimeGG/Assets/Scripts/Rewards/RewardController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/FontResizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/GridSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectMoveController.cs
  SlimeGG/Assets/Scripts/UIs/Controller/ObjectSizeController.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
  SlimeGG/Assets/TextMesh Pro/Fonts/neodgm SDF.asset
Labels: documentation, enhancement

#113 closes #78
  SlimeGG/Assets/Prefabs/Inventories/EvolutionCasePrefab.prefab
  SlimeGG/Assets/Resources/Jsons/Save/Items.json
  SlimeGG/Assets/Resources/Jsons/Save/Monsters.json
  SlimeGG/Assets/Scripts/Commons/Functions/MonsterCommonFunction.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/ContentController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/EvolutionCaseController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/MonsterInfoController.cs
  SlimeGG/Assets/Scripts/Inventories/Controllers/StatSlotController.cs
  SlimeGG/Assets/Scripts/Objects/Common/ElementStat.cs
  SlimeGG/Assets/Scripts/UIs/Managers/InventoryManager.cs
Labels: enhancement

#114 closes #112
  SlimeGG/Assets/Resources/Jsons/Dungeons/Beach1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Beach1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Cave1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Cave1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Desert1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Desert1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Forest1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Forest1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Highland1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Highland1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Iceland1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Iceland1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Lava1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Lava1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Meadow1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Meadow1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Ruin1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Ruin1.json.meta
  SlimeGG/Assets/Resources/Jsons/Dungeons/Swamp.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Swamps1.json
  SlimeGG/Assets/Resources/Jsons/Dungeons/Swamps1.json.meta
  SlimeGG/Assets/Resources/Jsons/Fields/BASIC1.json
  SlimeGG/Assets/Resources/Jsons/Fields/BASIC1.json.meta
  SlimeGG/Assets/Resources/Jsons/Fields/rrr.json
  SlimeGG/Assets/Resources/Jsons/Fields/tetet.json
  SlimeGG/Assets/Resources/Jsons/Monsters/RockBorn.json
  SlimeGG/Assets/Resources/Jsons/Monsters/RockBorn.json.meta
  SlimeGG/Assets/Resources/Jsons/Save/DungeonHistory.json
  SlimeGG/Assets/Resources/Jsons/Skills/PlanetSmash.json
  SlimeGG/Assets/Resources/Jsons/Skills/PlanetSmash.json.meta
  SlimeGG/Assets/Resources/Jsons/Skills/Proof.json
  SlimeGG/Assets/Resources/Jsons/Skills/Proof.json.meta
  SlimeGG/Assets/Scenes/BattleScene.unity
  SlimeGG/Assets/Scripts/Battles/Controller/EntrySlotController.cs
  SlimeGG/Assets/Scripts/Battles/Manager/BattleManager.cs
  SlimeGG/Assets/Scripts/Commons/LocalDictionary.cs
  SlimeGG/Assets/Scripts/Commons/Managers/DataManager.cs
  SlimeGG/Assets/Scripts/UIs/Generators/GridCellGenerator.cs
Labels: enhancement
